# Estas são chaves que estão associadas a possivelmente mais de
# um @NRO-ID-CNPQ e, portanto, representam itens que devem ser
# separados do CV no qual foram especificados, por poderem
# pertencer a mais de uma pessoa.

item_keys = {'APRESENTACAO-DE-OBRA-ARTISTICA', 'APRESENTACAO-DE-TRABALHO', 'APRESENTACAO-EM-RADIO-OU-TV', 'ARRANJO-MUSICAL', 'ARTES-CENICAS', 'ARTES-VISUAIS', 'ARTIGO-ACEITO-PARA-PUBLICACAO', 'ARTIGO-PUBLICADO', 'BANCA-JULGADORA-PARA-AVALIACAO-CURSOS', 'BANCA-JULGADORA-PARA-CONCURSO-PUBLICO', 'BANCA-JULGADORA-PARA-LIVRE-DOCENCIA', 'BANCA-JULGADORA-PARA-PROFESSOR-TITULAR', 'CAPITULO-DE-LIVRO-PUBLICADO', 'CARTA-MAPA-OU-SIMILAR', 'COMPOSICAO-MUSICAL', 'CULTIVAR-PROTEGIDA', 'CULTIVAR-REGISTRADA', 'CURSO-DE-CURTA-DURACAO', 'CURSO-DE-CURTA-DURACAO-MINISTRADO', 'DEMAIS-TRABALHOS', 'DESENHO-INDUSTRIAL', 'DESENVOLVIMENTO-DE-MATERIAL-DIDATICO-OU-INSTRUCIONAL', 'EDITORACAO', 'LIVRO-PUBLICADO-OU-ORGANIZADO', 'MANUTENCAO-DE-OBRA-ARTISTICA', 'MAQUETE', 'MARCA', 'MIDIA-SOCIAL-WEBSITE-BLOG', 'MUSICA', 'OBRA-DE-ARTES-VISUAIS', 'ORGANIZACAO-DE-EVENTO', 'OUTRA-PRODUCAO-ARTISTICA-CULTURAL', 'OUTRA-PRODUCAO-BIBLIOGRAFICA', 'OUTRA-PRODUCAO-TECNICA', 'OUTRAS-BANCAS-JULGADORAS', 'OUTRAS-PARTICIPACOES-EM-BANCA', 'OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS', 'PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO', 'PARTICIPACAO-EM-BANCA-DE-DOUTORADO', 'PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO', 'PARTICIPACAO-EM-BANCA-DE-GRADUACAO', 'PARTICIPACAO-EM-BANCA-DE-MESTRADO', 'PARTICIPACAO-EM-CONGRESSO', 'PARTICIPACAO-EM-ENCONTRO', 'PARTICIPACAO-EM-EXPOSICAO', 'PARTICIPACAO-EM-FEIRA', 'PARTICIPACAO-EM-OFICINA', 'PARTICIPACAO-EM-OLIMPIADA', 'PARTICIPACAO-EM-SEMINARIO', 'PARTICIPACAO-EM-SIMPOSIO', 'PARTITURA-MUSICAL', 'PATENTE', 'PREFACIO-POSFACIO', 'PROCESSOS-OU-TECNICAS', 'PRODUTO-TECNOLOGICO', 'PROGRAMA-DE-RADIO-OU-TV', 'RELATORIO-DE-PESQUISA', 'SOFTWARE', 'SONOPLASTIA', 'TEXTO-EM-JORNAL-OU-REVISTA', 'TRABALHO-EM-EVENTOS', 'TRABALHO-TECNICO', 'TRADUCAO'}

# TODO: 'PROJETO-DE-PESQUISA' deveria ser incluído no conjunto,
# mas é um pouco diferente dos demais: em vez de estar associado
# com um ano específico, ele está associado a um intervalo
# @ANO-INICIO a @ANO-FIM. Além disso, em vez de estar numerado
# por @SEQUENCIA-PRODUCAO, ele está numerado por @SEQUENCIA-PROJETO
